final products = [
  {
    "id": 0,
    'title': 'Adidas Shoes',
    'price': 920.00,
    'imageUrl': 'assets/images/adidas-shoes-1.png',
    'company': 'Adidas',
    'sizes': [8, 9, 10, 11],
  },
  {
    "id": 1,
    'title': 'Bata\'s High Heels',
    'price': 635.00,
    'imageUrl': 'assets/images/high-heels-1.png',
    'company': 'Bata',
    'sizes': [9, 10, 12],
  },
  {
    "id": 2,
    'title': 'Campus Shoes',
    'price': 850.00,
    'imageUrl': 'assets/images/full-shoe.png',
    'company': 'Campus',
    'sizes': [8, 9, 10],
  },
  {
    "id": 3,
    'title': 'Men\'s Reebok Shoes',
    'price': 1005.00,
    'imageUrl': 'assets/images/nike-shoes-4.png',
    'company': 'Reebok',
    'sizes': [8, 9, 11],
  },
  {
    "id": 4,
    'title': 'Nike Shoes',
    'price': 1020.00,
    'imageUrl': 'assets/images/nike-shoes-3.png',
    'company': 'Nike',
    'sizes': [9, 11],
  },
  {
    "id": 5,
    'title': 'Sparx Shoes',
    'price': 675.00,
    'imageUrl': 'assets/images/nike-shoes-2.png',
    'company': 'Sparx',
    'sizes': [8, 9],
  },
];
